# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab6e69c7b0edbe0a542c2b929e84155e3893884c80c14b6b48bad70f528854c0ef7403c62a2e6e912fb80ccaaccf38cbed38adf374f07ff6cfad345231acebf

test:
  secret_key_base: 7c920c71d5b1db78f768917dddaa6848f40ee587f233b4ec7f599812a01e3c0ca3510d3437eab07bb272ec508607dbf17e89dc6697818060caffedec8d3b26ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
